run-test.sh.in: make the indentation make sense
The Python invocation is indented, because it's a command-line argument
for the sh invocation. The case shouldn't be.

Reviewed-by: Guillaume Desmottes <guillaume.desmottes@collabora.co.uk>
Bug: https://bugs.freedesktop.org/show_bug.cgi?id=65290

diff --git a/tests/twisted/run-test.sh.in b/tests/twisted/run-test.sh.in
--- a/tests/twisted/run-test.sh.in
+++ b/tests/twisted/run-test.sh.in
@@ -51,19 +51,19 @@ for i in $list ; do
     --config-file="${config_file}" \
     -- \
     @TEST_PYTHON@ -u "${test_src}/twisted/$i"
-    e=$?
-    case "$e" in
-        (0)
-            echo "PASS: $i"
-            ;;
-        (77)
-            echo "SKIP: $i"
-            ;;
-        (*)
-            any_failed=1
-            echo "FAIL: $i ($e)"
-            ;;
-    esac
+  e=$?
+  case "$e" in
+    (0)
+      echo "PASS: $i"
+      ;;
+    (77)
+      echo "SKIP: $i"
+      ;;
+    (*)
+      any_failed=1
+      echo "FAIL: $i ($e)"
+      ;;
+  esac
 done
 
 exit $any_failed
