Fail "make check" if you declare a GError*, leave it uninitialized and don't add a comment indicating that that's OK because you'll immediately use g_error_new (g_set_error asserts when it sees uninitialized GError*s, so they should be avoided). Fix the resulting "make check" failures.
20070405142608-53eee-78f4e7efb71548b36582106e52ed73734b6a36d7.gz

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -110,6 +110,14 @@ check-local::
 		echo "^^^ The above files contain tabs"; \
 		exit 1; \
 	fi
+	@echo "Checking for GError mistakes..."
+	@if grep -n '^ *GError *\*[a-zA-Z_][a-zA-Z0-9_]* *;' \
+		$(whitespace_sources); \
+	then \
+		echo "^^^ The above files contain uninitialized GError*s -"; \
+		echo "    they should be initialized to NULL"; \
+		exit 1; \
+	fi
 
 telepathy_gabble_LDADD = libgabble-convenience.la \
 			 $(top_builddir)/lib/telepathy-glib/libtelepathy-glib.la
